### ISSUE TITLE
Add nudge for the route selector

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#123]
(Based on feedback from Sava)

When the user opens the site for the first time, they see a map - but no routes, nor vehicles. Since nothing else happens, some might be confused about what to do next.

The UI needs a nudge that will hint them what to do to get started. Therefore:

- when the UI is loaded
- and there are no previously selected routes (e.g. from previous sessions)
- the nudge should be triggered

The nudge itself:
1. the route selection icon should bounce (a pulsating effect might also work, and other alternatives can be discussed)
2. its tooltip should be shown

**Comment by dasshield** [comment]
I'll take it
