### ISSUE TITLE
Show the user's current location, optionally

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#19]
We need to show the current location of a user, so they can figure out where they are, what is in their proximity and where the nearest vehicles are.

To keep the site _privacy-preserving_, this must be an optional feature. The workflow is like this:

- open up the page, scroll around and observe the vehicle positions (at this stage there's no sign of a location request)
- the user presses a `show my position` button - and _only then_ do we request the permission to get location data

This will also make the site less annoying, as we won't expose people to unexpected pop-ups.

**Comment by roata** [comment]
Duplicate of #9 .

**Comment by roata** [comment]
@pedramp, this is a dupe of #9 (which was written in Romanian), but this one is its English equivalent. I thought you might consider it a low-hanging fruit for your Hacktoberfest spree.

Here are some places on the Internet where a comparable feature is discussed.
- https://stackoverflow.com/questions/54099898/react-locate-on-map
- https://github.com/fullhdpixel/react-leaflet-locate-control
- https://github.com/domoritz/leaflet-locatecontrol/


Maybe you know how to do it even better, I liked your simple and elegant approach for the smooth markers feature :-)

**Comment by pedramp** [comment]
@roata thanks, I’ll check it soon ;)
