### ISSUE TITLE
Save preferences

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#21]
There are a number of options that users can customize, or that could be "sticky":

- last selected route
- language preference
- maybe in the future - favourite locations

The site should give people an option to remember this information for future use. This functionality must be invoked **only after the user pressed** "Remember my preferences".

This is to ensure that we are not going to annoy users (like the "cookie disclaimers" do). The logic must be like this:

- forget everything, remember nothing
- don't ask any questions
- but if the user explicitly expressed their wish to store data - then do so

Discuss - what mechanism is suitable for this? Local storage? Cookies? Encoding this stuff inside the URL parameters?

**Comment by iamandrewluca** [comment]
Strategy is to use Local Storage. https://caniuse.com/#feat=mdn-api_window_localstorage
For heavy storage in browser IndexedDB can be used. https://caniuse.com/#feat=indexeddb

**Comment by iamandrewluca** [comment]
Now all settings are saved in `localStorage`
