### ISSUE TITLE
Correct station marker offsets when zooming in and out

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#27]
There's an artifact that occurs when zooming in and out - the station markers appear to be offset, but they get into their proper positions when zooming in.

This effect should be eliminated.

![vokoscreen-2019-09-29_16-48-12](https://user-images.githubusercontent.com/48152696/65834202-0d464380-e2d9-11e9-910f-3b471ef23de8.gif)

**Comment by roata** [comment]
Related issues and their solutions:

- https://gis.stackexchange.com/questions/222971/how-can-i-prevent-leaflet-from-moving-my-marker-while-zooming-into-the-map
- https://stackoverflow.com/questions/17875438/leafletjs-markers-move-on-zoom

**Comment by iamandrewluca** [comment]
I think we only need to retrigger a render, and this will fix the problem.
Zooming is represented by z axis. Adding a `key` prop to a react element, will trigger a render when key is changed.

**Comment by roata** [comment]
But wouldn't that be a performance issue? I am thinking of mobile users running this on their phones, it would suck if people hated our app because it drains their battery.

My other concern is that I don't know how to do it, actually - the stations are rendered automatically through the `GeoJSON` component, so we don't render each marker directly.

**Comment by iamandrewluca** [comment]
@roata yes I also always strugle about performance :slightly_smiling_face: 

In this case I think is the responsability of `GeoJSON` to rendre markers correctly. I'll investigate.

**Comment by roata** [comment]
This problem still exists.
