### ISSUE TITLE
Show station name in popup when clicking its marker

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#28]
At the moment the stations have no names, although the information is available in the GeoJSON. What we need is:

1. the station name should be shown in a tooltip when the mouse is over it
2. for users who don't have a mouse (e.g., phones) this is additionally shown in a popup when the marker is clicked.

All the station data can be found in `src/data/route_<station_id>_stations.json`.

**Comment by iamandrewluca** [comment]
Fixed in #47
