### ISSUE TITLE
Smooth marker movement

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#33]
The GPS data arrives every 3..5s, so the vehicle markers are "jumping" from the previous position to the current one. This can be improved, by letting the marker drift smoothly to the new location, giving the impression of a continuous, rather than discrete change.

This plugin promises to do the trick: https://www.npmjs.com/package/leaflet-drift-marker

**Comment by pedramp** [comment]
An easy way that seems to me without any code/plugin, We can add `transition: transform 4s;` CSS to arrow container, means 4 sec to move and before the finish (after 3.5s) marker should move to a newest position, that means marker always is moving smoothly!

**Comment by roata** [comment]
Thanks for the suggestion, and generally - for expressing interest in the project :-)

I tried this trick and it seems to work well, but there is an issue that occurs when zooming in and out: 
![vokoscreen-2019-10-04_13-12-57](https://user-images.githubusercontent.com/48152696/66203627-194f4e00-e6a9-11e9-98b1-512400fc44ec.gif)
animated: https://giphy.com/gifs/TIEpO0eNRtGfE1sFXQ

As I am not CSS guru, I have no idea how to address this side-effect.

Another point - we don't know for sure how soon the new data will arrive. As a rule, new telemetry is received between 3..5s, but there could be delays - would that constitute a problem?

**Comment by roata** [comment]
@pedramp  Salam! Thanks for the suggestion, and generally - for expressing interest in the project :-)

I tried this trick and it seems to work well, but there is an issue that occurs when zooming in and out: 
![vokoscreen-2019-10-04_13-12-57](https://user-images.githubusercontent.com/48152696/66203627-194f4e00-e6a9-11e9-98b1-512400fc44ec.gif)
animated: https://giphy.com/gifs/TIEpO0eNRtGfE1sFXQ

As I am not CSS guru, I have no idea how to address this side-effect.

Another point - we don't know for sure how soon the new data will arrive. As a rule, new telemetry is received between 3..5s, but there could be delays - would that constitute a problem?

**Comment by roata** [comment]
@pedramp, on a second thought, I see that even the current implementation has that; the difference is that it is not so obvious, because it lacks the `transition` effect. So I guess it wouldn't hurt if we just went ahead and did it. However, if you can suggest a solution for that too - that would be fantastic.

For example, could we set the transition time to 0 when we see that the zooming feature is invoked?


By the way, are you aware of the `hacktoberfest` initiative? You can make this change, then issue a pull request, and it will count toward your target of 5 PRs. More details are available on hacktoberfest.digitalocean.com

**Comment by pedramp** [comment]
hey Roata, it's a good idea to disable `transform` in zooming mode! I'll send PR soon :)

**Comment by pedramp** [comment]
but if we want to show animation correctly we should know the correct dealy(our default is 4s), without correct time, I guess some times we should see very minor lacks in our animation.

**Comment by pedramp** [comment]
@roata PR submitted #34 34
