### ISSUE TITLE
Implement route matching

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#36]
Due to the fact that raw GPS telemetry data is a bit noisy and inaccurate, the vehicle markers are slightly off the actual route. While this is not critical, i.e. the site still serves its function and makes peoples' lives better, a polished product should look better.

This is what I mean:
![image](https://user-images.githubusercontent.com/48152696/66232246-baa9c480-e6e8-11e9-96b9-ddc3f26b3087.png)

Instead of showing the raw position, we should project the marker onto the line segment where it ought to be, creating the illusion that it really moves on the route.

**Comment by leanu** [comment]
If you have 'segments', need to find closest segment, and 'project' transport to it. But as I see, segments are pretty raw, from osm, sometimes they cross the road, and are in both direction the same. I mean, it would be nice to have position not in the mid of the road, but on the right half, depending on the dirrection.

**Comment by roata** [comment]
It would definitely be nicer, but this would require an additional effort - either to make OSM data more detailed, or to post-process it after we retrieve it. I don't know of a way to do that easily. Have you got any ideas?

**Comment by roata** [comment]
The matched data are now available for beta testing, the information is posted to the MQTT topic `telemetry/transport/chiK8n/1/1/+` (the last element is the tracker ID).

You can try it with `mosquitto_sub -h opendata.dekart.com -p 1945 -t telemetry/transport/chiK8n/1/1/+`.


Before this is a part of the mainstream version, we need:
1. A debugging aid for visualizing map data, to see how well the matching works and tune the algorithm's parameters. It could be an HTML page that one can open locally and see live data. @iamandrewluca, do you have any suggestions about the easiest way to test this?
2. Eventually, the switch to MQTT transport must be accomplished https://github.com/roataway/web-ui/issues/81, because redirecting the data between the legacy (AMQP) and new (MQTT-based) systems will result in infinite loops.

**Comment by roata** [comment]
This was resolved by applying changes to the backend, hence there is no specific commit to link to.

The map will now snap the marker to the nearest road, found within a radius of 10m. There will be false positives, of course. However, this change brings the UI to a "good enough" level that balances aesthetics and practicality.

This can be improved, when more people join the project and more time can be dedicated to this issue.
