### ISSUE TITLE
Settle on internal format for vehicle metadata

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#38]
Currently information about vehicles and route names is stored in a CSV file, the argument in favour of this is that CSV files are more likely to be understood by domain experts (folks from the public transport organizations), because they can be edited in Excel like a table. Thus, they won't have to deal with the problem of unbalanced braces or missing commas.

If processing this in JS causes unnecessary headaches, we can resolve it by writing a `csv2json` helper tool (or using one of those that already exist). This way the software will get what it wants, while domain experts get what they want.

This seems like a reasonable compromise to me, and besides that, there is room for a potentially better solution - e.g. importing data directly from a Google Sheets spreadsheet, or something like that.

@iamandrewluca, how much of a nuisance is the presence of CSV files, and what user-friendly alternatives can we try?

**Comment by iamandrewluca** [comment]
Ok I agree. We can keep CSV files. I know a solution that will import them as JSON in the program.
