### ISSUE TITLE
Re-factor the route metadata into a separate project

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#43]
Create a project called `route-data` within the organization, it should contain:

- a readme
- the JSON stuff that we currently have in `data/`
- the stuff currently in `tools/`

**Comment by roata** [comment]
What about `vehicles.csv` and `routes.csv`? That is also data that might be taken out, but I am not sure where. Vehicles are not routes, so probably not in https://github.com/roataway/route-data :-) What do you think, @iamandrewluca ?

**Comment by iamandrewluca** [comment]
Move them also, pute them in root folder in `route-data`

**Comment by roata** [comment]
Done. Everything is in the other repo, as you requested. I'll let you delete them from this one, as you see fit.

p.s. 
> ...
If not another country, then maybe at least another city :-)

**Comment by iamandrewluca** [comment]
I thought of implementing multiple cities in the same app, map.md from simpals do this.
