### ISSUE TITLE
Zoom in: maximum level constraint

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#48]
When zooming in beyond a certain level, the entire map turns gray. The UI should prevent people from zooming in that far; the last zoom-level that is still visible is sufficiently detailed for any practical purpose.

See this GIF as a demo of this effect:
https://media.giphy.com/media/YlSfDHaiixJS4LKDRq/giphy.gif

**Comment by zilehuda** [comment]
taking it.

**Comment by roata** [comment]
Cool, thanks! Consider taking this one too; I am no expert in this matter, but it seems to be a low-hanging fruit: https://github.com/roataway/web-ui/issues/51

**Comment by zilehuda** [comment]
PR #52

**Comment by roata** [comment]
Resolved in https://github.com/roataway/web-ui/pull/52
