### ISSUE TITLE
Show zoom control

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#51]
At the moment we don't have +/- buttons on the map, so the only way to zoom in and out is to use 2-finger touch or a scroll-wheel (if you have a mouse).

When you use the software on a phone, you might have only one hand available (the other one is holding a bag, a child or a fellow human hand) - so zooming in and out will be challenging.

This can be resolved by showing the zoom controls, like this:
![image](https://user-images.githubusercontent.com/48152696/66701045-c3f1ed00-ecf7-11e9-99f8-405e023fb7e8.png)

What we need:

1. the `+/-` buttons to be shown
2. they must be placed in an area easy to reach with the thumb (see the image below for a reference)
3. bonus: single-finger zooming (via tap-and-drag up/down, like on Google Maps) would be nice and would make everyone happy

![image](https://user-images.githubusercontent.com/48152696/66701104-aec98e00-ecf8-11e9-899f-9e5a2ec824b4.png)

Obviously it should not be on the top side of the screen - that's unreachable. I am inclined to put it on the bottom-left side, with a slight offset from the edge. This will discriminate against left-handed users, so a separate issue will be created to fully address this matter.

**Comment by zilehuda** [comment]
taking this

**Comment by zilehuda** [comment]
PR #56
