### ISSUE TITLE
Left-handed UI

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#54]
Since this is likely to be used by people who travel in public transport, we have to consider the "one-hand usage" experience, hence dexterity plays a greater role than in a typical interface.

Here's what happens when a user chooses a "left-handed" mode of the UI, the map controls migrate to the right side of the screen:
- `+/-` zoom buttons
- `my location`
- `pick route`

**Comment by hendaoui** [comment]
Assign it to me :)

**Comment by hendaoui** [comment]
if the user chooses a "left-handed" mode, only the `+/-` zoom buttons will migrate to the left while `my location` and `pick route` already at right!

**Comment by hendaoui** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6974404/66719445-b6b42b80-ede7-11e9-8dc5-a0f7ac5dbf75.gif)
These are my changes, can i make a new PR ?
