### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#55]
We support 3 languages at the moment, based on the expected target audience: Romanian, Russian, English.

We need to set one of these languages by default, based on the `Accept-language` HTTP header. Besides that, users should be able to override that setting. For example, my system locale might be set to Romanian, but I prefer the UI to be in English.

Thus, the logic for prioritizing the language choice is as follows:
1. use the custom language setting (if it was set)
2. use the auto-detected language from `Accept-language` (if supported)
3. otherwise fallback to English as the default

**Note**: refrain from using flags as language indicators, as this can blow up in unexpected ways and nothing good will come out of it.

**Comment by hendaoui** [comment]
I'm working on it, assign it to me :)

**Comment by hendaoui** [comment]
Does the `Accept-language` header will be returned in the response ? and what are the possible values

**Comment by roata** [comment]
`Accept-Language` is a part of the _request_, and it indicates the client's preference, i.e. "I would prefer the page you give me back to be in language X".

A related header, `Content-Language` is a part of the _response_, and it indicates what language the response is in. It doesn't necessarily have to match the user's declared preferences, let's say you send a request saying "I want a page in Chinese", but the server doesn't support Chinese - so it sends back whatever it hopes most people would understand, say English.

In this particular case, our intention is to rely on the presence of `Accept-Language` in the request headers, and use it to return a response in the user's preferred language, if we can.

The syntax of the possible values for it as defined in RFC 2616, but you can also have a look at this page for a summary: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

In the case of our software, the languages we support at the moment are Romanian, Russian and English.

**Comment by iamandrewluca** [comment]
Notes:
* `navigator.languages`
* `navigator.language`
