### ISSUE TITLE
Tutoring for newbie-contributors

### ISSUE THREAD

**Issue by roata** [roataway/web-ui#7]
@iamandrewluca, would it be possible to create some simple issues fit for the `good first issue` tag, which we could distribute to a pool of potential contributors?

Such tasks would have to be broken down into smaller ones, at a level of complexity that would not scare them. This could happen at 2 levels:

1. self-contained tasks which say "use technology X to do Y"
2. supervised tasks, which will require some hand-holding, such that a newbie doesn't trip on their own shoe-laces :-) I can supervise them in all matters related to MQTT, websockets, message-formats, data structures, HTTP and general common sense. However, I have no React skills yet; so I'll have to learn it myself first.
3. [bonus] tasks with a nudge that I will implement after you tell me, in broad terms, what needs to be done. This is like a hybrid of 1 and 2 - I have no experience with React, but I can RTFM and find my own way once the general direction was pointed out.

**Comment by Leftere** [comment]
Hi guys, I have a general basic understanding of react, components lifecycle, and I'm currently working on upscaling my skills. I only have about a year of experience working with front-end technologies and want to learn more and contribute. 

Let's see what do we have so far and what the next priorities.  

Yes, Please someone hold my hand :- )

**Comment by roata** [comment]
@Leftere, will you be able to create the route-selection dialog? https://github.com/roataway/web-ui/issues/25

**Comment by Leftere** [comment]
@roata sorry, just got a new job and have been working on some other projects. I will try to drop in some time later

**Comment by roata** [comment]
I hope you enjoy your new job; recently I switched locations too :-)

I started working on this ticket myself, perhaps you can provide some tips about 
 the 6 points at the bottom: https://github.com/roataway/web-ui/commit/0376484749771f45fb78dfdacaa7585aaca33417

**Comment by roata** [comment]
Since there's no flood of new contributors, this issue is not so relevant. For future reference:

- The easier ones have a "good first issue" tag, so new contributors can use them as starting points.
- Guidance can be obtained here, or on https://roataway.zulipchat.com/
